[
server
]
   enableXsrfProtection = false

   [
browser
]
   gatherUsageStats = false

   [
theme
]
   primaryColor = "#F63366"
   backgroundColor = "#FFFFFF"
   secondaryBackgroundColor = "#F0F2F6"
   textColor = "#262730"
   font = "sans serif"

   [
packages
]
   poppler-utils = "==0.1.0"
